-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 17:18:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EPIS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EPIS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EPIS` DEFAULT CHARACTER SET utf8 ;
USE `EPIS` ;

-- -----------------------------------------------------
-- Table `EPIS`.`Identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Identificacion` (
  `id_Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Estado` ENUM('ACTIVO', 'INACTIVO') NOT NULL,
  PRIMARY KEY (`id_Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Persona` (
  `id_Persona` INT NOT NULL AUTO_INCREMENT,
  `Identificacion_id_Identificacion` INT NOT NULL,
  `Identificacion` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo_Electronico` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Persona`),
  INDEX `fk_Persona_Identificacion1_idx` (`Identificacion_id_Identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Identificacion1`
    FOREIGN KEY (`Identificacion_id_Identificacion`)
    REFERENCES `EPIS`.`Identificacion` (`id_Identificacion`)
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(65) NOT NULL,
  `Persona_id_Persona` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  INDEX `fk_Usuario_Persona_idx` (`Persona_id_Persona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `EPIS`.`Persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Entidad` (
  `id_Entidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Nit` INT(20) NOT NULL,
  `Telefono` VARCHAR(25) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL,
  `Estado` ENUM('ACTIVA', 'INACTIVA') NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `Tipo` ENUM('PRINCIPAL', 'SEDE') NOT NULL,
  PRIMARY KEY (`id_Entidad`),
  UNIQUE INDEX `Nit_UNIQUE` (`Nit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Rol` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` ENUM('ADMIN', 'PROFESIONAL', 'PASANTE') NOT NULL,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Registro_EP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Registro_EP` (
  `id_Registro_EP` INT NOT NULL AUTO_INCREMENT,
  `Fecha` TIMESTAMP NOT NULL,
  `Estado` ENUM('ACTIVA', 'INACTIVA') NOT NULL,
  `Registro_EPcol` VARCHAR(45) NULL,
  `Entidad_id_Entidad` INT NOT NULL,
  `Persona_id_Persona` INT NOT NULL,
  `Rol_id_Rol` INT NOT NULL,
  PRIMARY KEY (`id_Registro_EP`),
  INDEX `fk_Registro_EP_Entidad1_idx` (`Entidad_id_Entidad` ASC) VISIBLE,
  INDEX `fk_Registro_EP_Persona1_idx` (`Persona_id_Persona` ASC) VISIBLE,
  INDEX `fk_Registro_EP_Rol1_idx` (`Rol_id_Rol` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_EP_Entidad1`
    FOREIGN KEY (`Entidad_id_Entidad`)
    REFERENCES `EPIS`.`Entidad` (`id_Entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_EP_Persona1`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `EPIS`.`Persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_EP_Rol1`
    FOREIGN KEY (`Rol_id_Rol`)
    REFERENCES `EPIS`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Menu` (
  `id_Menu` INT NOT NULL AUTO_INCREMENT,
  `Icono` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ruta` TEXT NOT NULL,
  `Orden` INT NOT NULL,
  PRIMARY KEY (`id_Menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Permisos` (
  `id_Permisos` INT NOT NULL AUTO_INCREMENT,
  `Rol_id_Rol` INT NOT NULL,
  `Menu_id_Menu` INT NOT NULL,
  PRIMARY KEY (`id_Permisos`),
  INDEX `fk_Permisos_Menu1_idx` (`Menu_id_Menu` ASC) VISIBLE,
  INDEX `fk_Permisos_Rol1_idx` (`Rol_id_Rol` ASC) VISIBLE,
  CONSTRAINT `fk_Permisos_Menu1`
    FOREIGN KEY (`Menu_id_Menu`)
    REFERENCES `EPIS`.`Menu` (`id_Menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Rol1`
    FOREIGN KEY (`Rol_id_Rol`)
    REFERENCES `EPIS`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Bodega` (
  `id_Bodega` INT NOT NULL AUTO_INCREMENT,
  `Cod_Bodega` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo_Bodega` ENUM('GRANDE', 'PEQUEÑA') NOT NULL,
  `Estado` ENUM('ACTIVA', 'INACTIVA') NOT NULL,
  `Entidad_id_Entidad` INT NOT NULL,
  PRIMARY KEY (`id_Bodega`),
  INDEX `fk_Bodega_Entidad1_idx` (`Entidad_id_Entidad` ASC) VISIBLE,
  CONSTRAINT `fk_Bodega_Entidad1`
    FOREIGN KEY (`Entidad_id_Entidad`)
    REFERENCES `EPIS`.`Entidad` (`id_Entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Proveedor` (
  `id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Nit` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Inventario` (
  `id_Inventario` INT NOT NULL AUTO_INCREMENT,
  `Cod_Inventario` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Descripcion` VARCHAR(250) NOT NULL,
  `Bodega_id_Bodega` INT NOT NULL,
  PRIMARY KEY (`id_Inventario`),
  INDEX `fk_Inventario_Bodega1_idx` (`Bodega_id_Bodega` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Bodega1`
    FOREIGN KEY (`Bodega_id_Bodega`)
    REFERENCES `EPIS`.`Bodega` (`id_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Tipo_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Tipo_Producto` (
  `id_Tipo_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_Tipo_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Producto_id_Tipo_Producto` INT NOT NULL,
  `Cod_Producto` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cantidad_Producto` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Estado` ENUM('DISPONIBLE', 'AGOTADO') NOT NULL,
  `Proveedor_id_Proveedor` INT NOT NULL,
  `Bodega_id_Bodega` INT NOT NULL,
  PRIMARY KEY (`id_Producto`),
  INDEX `fk_Producto_Tipo_Producto1_idx` (`Tipo_Producto_id_Tipo_Producto` ASC) VISIBLE,
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_id_Proveedor` ASC) VISIBLE,
  INDEX `fk_Producto_Bodega1_idx` (`Bodega_id_Bodega` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Tipo_Producto1`
    FOREIGN KEY (`Tipo_Producto_id_Tipo_Producto`)
    REFERENCES `EPIS`.`Tipo_Producto` (`id_Tipo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_id_Proveedor`)
    REFERENCES `EPIS`.`Proveedor` (`id_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Bodega1`
    FOREIGN KEY (`Bodega_id_Bodega`)
    REFERENCES `EPIS`.`Bodega` (`id_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Pedidos` (
  `id_Pedidos` INT NOT NULL AUTO_INCREMENT,
  `Fecha` TIMESTAMP NOT NULL,
  `Detalle_Pedido` TEXT NOT NULL,
  `Detalle_Entrega` TEXT NOT NULL,
  `Entidad_id_Entidad` INT NOT NULL,
  PRIMARY KEY (`id_Pedidos`),
  INDEX `fk_Pedidos_Entidad1_idx` (`Entidad_id_Entidad` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Entidad1`
    FOREIGN KEY (`Entidad_id_Entidad`)
    REFERENCES `EPIS`.`Entidad` (`id_Entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EPIS`.`Restricciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EPIS`.`Restricciones` (
  `id_Restricciones` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Detalle` VARCHAR(250) NOT NULL,
  `Producto_id_Producto` INT NOT NULL,
  PRIMARY KEY (`id_Restricciones`),
  INDEX `fk_Restricciones_Producto1_idx` (`Producto_id_Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Restricciones_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `EPIS`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
